### ISSUE TITLE
Debugger error with unit tests

### ISSUE THREAD

**Issue by rich-hart** [openstax/cnx-publishing#104]
If I run the following command to initiate unit tests with the python debugger 

``` shell
python -m pdb setup.py test 
```

the publishing tests will load properly and run to completion the first time.  When the debugger is finished it will automatically restart the program and attempt to run the tests a second time.  However, when the tests are run a second time, this error comes up:

``` .pytb
----------------------------------------------------------------------
Ran 68 tests in 141.049s

OK
The program exited via sys.exit(). Exit status:  False
> /Users/openstax/workspace/openstax_scripts/development/cnx-publishing/setup.py(2)<module>()
-> import sys
(Pdb) c
running test
running egg_info
writing requirements to cnx_publishing.egg-info/requires.txt
writing cnx_publishing.egg-info/PKG-INFO
writing top-level names to cnx_publishing.egg-info/top_level.txt
writing dependency_links to cnx_publishing.egg-info/dependency_links.txt
writing entry points to cnx_publishing.egg-info/entry_points.txt
reading manifest file 'cnx_publishing.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cnx_publishing.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "setup.py", line 2, in <module>
    import sys
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-publishing/cnxpublishing/tests/test_db.py", line 25, in <module>
    from pyramid import testing
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/pyramid-1.5.4-py2.7.egg/pyramid/testing.py", line 5, in <module>
    from zope.interface import (
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/__init__.py", line 57, in <module>
    _wire()
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/interface.py", line 669, in _wire
    from zope.interface.interfaces import IAttribute
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/interfaces.py", line 770, in <module>
    class ObjectEvent(object):
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/declarations.py", line 314, in __call__
    classImplements(ob, *self.interfaces)
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/declarations.py", line 252, in classImplements
    spec = implementedBy(cls)
  File "/Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/declarations.py", line 177, in implementedByFallback
    if isinstance(spec, Implements):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/openstax/workspace/openstax_scripts/development/lib/python2.7/site-packages/zope.interface-4.1.2-py2.7-macosx-10.10-intel.egg/zope/interface/declarations.py(177)implementedByFallback()
-> if isinstance(spec, Implements):
(Pdb)
```

The only way I can get around the error is by exiting the debugger completely and running the tests from the command line again, meaning that the breakpoints I used to debug the program will be lost.  What is interesting is that cnx-archive does not throw these errors when the debugger /tests are restarted.  

This isn't a critical bug but it would definitely make my life easier if there was a way to fix it.

**Comment by karenc** [comment]
This is interesting.  I only get this error after all the tests finish running.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
