### ISSUE TITLE
May need to roll back on error when baking

### ISSUE THREAD

**Issue by sisiz** [openstax/cnx-publishing#160]
`
2017-06-27 13:31:10,012 DEBUG [cnxpublishing][MainThread] Finished exporting module_ident=21 ident_hash=e79ffde3-7fb4-4af3-9ec8-df648b391597@6.2
2017-06-27 13:31:10,012 DEBUG [cnxpublishing][MainThread] Finished exporting module_ident=21 ident_hash=e79ffde3-7fb4-4af3-9ec8-df648b391597@6.2
2017-06-27 13:31:10,326 DEBUG [cnxpublishing][MainThread] Finished processing module_ident=21 ident_hash=e79ffde3-7fb4-4af3-9ec8-df648b391597@6.2 with a final state of 'current'.
2017-06-27 13:31:10,580 ERROR [cnxpublishing][MainThread] Logging an uncaught exception during baking
Traceback (most recent call last):
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/subscribers.py", line 77, in baking_processor
    bake(binder, publisher, message, cursor=cursor)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/db.py", line 61, in wrapped
    return func(*args, **kwargs)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/bake.py", line 78, in bake
    publish_collated_tree(cursor, tree)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/publish.py", line 450, in publish_collated_tree
    tree = _insert_tree(cursor, tree, is_collated=True)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/publish.py", line 306, in _insert_tree
    is_latest=is_latest, is_collated=is_collated))
IntegrityError: duplicate key value violates unique constraint "trees_unique_doc_idx"
DETAIL:  Key (documentid, is_collated)=(21, t) already exists.

2017-06-27 13:31:10,583 DEBUG [cnxpublishing][MainThread] Finished processing module_ident=21 ident_hash=e79ffde3-7fb4-4af3-9ec8-df648b391597@6.2 with a final state of 'errored'.
[2017-06-27 13:31:10,639: ERROR/PoolWorker-3] Task cnxpublishing.subscribers.baking_processor[7d8fd127-0b3e-49b1-aa16-5d34dfb8f1b9] raised unexpected: InternalError('current transaction is aborted, commands ignored until end of transaction block\n',)
Traceback (most recent call last):
  File "/Users/mackenziegaskin/src/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/tasks.py", line 30, in __call__
    return super(PyramidAwareTask, self).__call__(*args, **kwargs)
  File "/Users/mackenziegaskin/src/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/db.py", line 67, in wrapped
    return func(*args, **kwargs)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/subscribers.py", line 88, in baking_processor
    update_module_state(cursor, module_ident, state)
  File "/Users/mackenziegaskin/src/cnx-publishing/cnxpublishing/db.py", line 1434, in update_module_state
    ) WHERE module_ident = %s""", (state_name, module_ident))
InternalError: current transaction is aborted, commands ignored until end of transaction block
`

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
