### ISSUE TITLE
Capture ValueError coming out of cnx-epub

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-publishing#85]
Catch this Error and be able to report which piece of content and which publication this error is occurring.

Example:

```
2015-02-20 14:00:37,312 ERROR [waitress][Dummy-3] Exception when serving /publications
Traceback (most recent call last):
  File "/opt/beta/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/opt/beta/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/opt/beta/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/opt/beta/local/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_publishing-0.2.0-py2.7.egg/cnxpublishing/views.py", line 53, in publish
    cursor, epub, epub_upload, is_pre_publication)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_publishing-0.2.0-py2.7.egg/cnxpublishing/db.py", line 619, in add_publication
    binder = cnxepub.adapt_package(package)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 48, in adapt_package
    return _node_to_model(tree, package)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 211, in _node_to_model
    lucent_id=lucent_id)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 211, in _node_to_model
    lucent_id=lucent_id)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 211, in _node_to_model
    lucent_id=lucent_id)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 219, in _node_to_model
    result = adapt_item(package_item, package)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 60, in adapt_item
    model = DocumentPointerItem(item, package)
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/adapters.py", line 255, in __init__
    metadata = DocumentPointerMetadataParser(self._html)()
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/html_parsers.py", line 87, in __call__
    return self.metadata
  File "/opt/beta/local/lib/python2.7/site-packages/cnx_epub-0.6.0-py2.7.egg/cnxepub/html_parsers.py", line 107, in metadata
    "A value for '{}' could not be found.".format(key))
ValueError: A value for 'title' could not be found.
```

**Comment by pumazi** [comment]
The issue illustrated here is because of Connexions/cnx-epub#37

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
